#!/bin/bash
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
OS1=$(lsb_release -si)
echo "Installing Plex Media Server . . . ."
if [ `getconf LONG_BIT` = "64" ]; then
  wget -c https://downloads.plex.tv/plex-media-server/1.10.0.4523-648bc61d4/plexmediaserver_1.10.0.4523-648bc61d4_amd64.deb >> $logfile 2>&1
  sudo apt-get install -f >> $logfile 2>&1
  rm plexmediaserver_*_amd64.deb
else
  wget -c https://downloads.plex.tv/plex-media-server/1.10.0.4523-648bc61d4/plexmediaserver_1.10.0.4523-648bc61d4_i386.deb >> $logfile 2>&1
  sudo apt-get install -f >> $logfile 2>&1
  rm plexmediaserver_*_i386.deb
fi

echo ""
echo "Plex Media Server is installed"
echo ""
echo "To enable remote access, set up ssh tunnel;"
echo "and access - http://$IPADDRESS1:32400/web"
echo "For initial Plex Setup check : "
echo "https://github.com/dannyti/sboxsetup/wiki/Initial-set-up-of-Plex-Media-Server"
echo ""
