#!/bin/bash
IPADDRESS1=`cat /etc/seedbox-from-scratch/hostname.info`
logfile="/dev/null"
OS1=$(lsb_release -si)
if [ `getconf LONG_BIT` = "64" ]; then
  echo "Installing Emby Media Server . . . ."
  wget https://github.com/MediaBrowser/Emby/releases/download/3.2.70.0/emby-server-deb_3.2.70.0_amd64.deb >> $logfile 2>&1
  dpkg -i emby-server-deb_3.2.70.0_amd64.deb >> $logfile 2>&1
  rm emby-server-deb_*_amd64.deb
else
  echo "Sorry, Emby Media Server is for 64bit systems only."
  echo ""
  exit 0
fi
echo ""
echo "Emby Media Server is installed"
echo ""
echo "To enable remote access, set up ssh tunnel;"
echo "and access - http://$IPADDRESS1:8096"
echo ""
