#!/bin/bash

# OpenVPN server add user script
# Usage: vpnadduser name [zip password]

bold="\033[1m"
normal="\033[0m"

if [ -z "$1" ]; then
	ERRORMSG="No client name supplied"
	logger "VPN-ADD-USER::ERROR - $ERRORMSG"
	echo $ERRORMSG
	exit 1
fi

if [[ "$EUID" -ne 0 ]]; then
	ERRORMSG="Sorry, you need to run this as root"
	logger "VPN-ADD-USER::ERROR - $ERRORMSG"
	echo $ERRORMSG
	exit 1
fi

if [[ -e /etc/openvpn/server.conf ]]; then

	OPENVPNPORT1=`cat /etc/seedbox-from-scratch/openvpn.info`

	newclient () {
		# Generates the custom client.ovpn
		cp /etc/openvpn/client-template.txt $homeDir/$1.ovpn
		echo "<ca>" >> $homeDir/$1.ovpn
		cat /etc/openvpn/easy-rsa/pki/ca.crt >> $homeDir/$1.ovpn
		echo "</ca>" >> $homeDir/$1.ovpn
		echo "<cert>" >> $homeDir/$1.ovpn
		cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >> $homeDir/$1.ovpn
		echo "</cert>" >> $homeDir/$1.ovpn
		echo "<key>" >> $homeDir/$1.ovpn
		cat /etc/openvpn/easy-rsa/pki/private/$1.key >> $homeDir/$1.ovpn
		echo "</key>" >> $homeDir/$1.ovpn
		echo "key-direction 1" >> $homeDir/$1.ovpn
		echo "<tls-auth>" >> $homeDir/$1.ovpn
		cat /etc/openvpn/tls-auth.key >> $homeDir/$1.ovpn
		echo "</tls-auth>" >> $homeDir/$1.ovpn
	}

	IP=$(wget -qO- ipv4.icanhazip.com)
	homeDir="/var/www"
	CLIENT="$1"
    	PASSWORD="$2"
	vpnup="/etc/seedbox-from-scratch/vpn_up.bat"
	vpndown="/etc/seedbox-from-scratch/vpn_down.bat"
	clientup="$homeDir/$1_up.bat"
	clientdown="$homeDir/$1_down.bat"
    
	cd /etc/openvpn/easy-rsa/
	./easyrsa build-client-full $CLIENT nopass
	if [ $? -eq 0 ]
	then
		# Generates the custom client.ovpn
		newclient "$CLIENT"
		cd $homeDir
		if [ -z "$2" ]; then
			if [ -z "$3" ]; then
				zip $CLIENT.zip $CLIENT.ovpn
			else
				cp $vpnup $clientup
				cp $vpndown $clientdown
				zip $CLIENT.zip $CLIENT.ovpn "$1"_up.bat "$1"_down.bat
			fi
		else
			if [ -z "$3" ]; then
				zip --password $PASSWORD $CLIENT.zip $CLIENT.ovpn
			else
				cp $vpnup $clientup
				cp $vpndown $clientdown
				zip --password $PASSWORD $CLIENT.zip $CLIENT.ovpn "$1"_up.bat "$1"_down.bat
			fi
		fi
		rm $CLIENT.ovpn "$1"_up.bat "$1"_down.bat
	else
    		echo
		echo "No client file created!"
	fi
	exit
else
	ERRORMSG="OpenVPN not installed"
	logger "VPN-ADD-USER::ERROR - $ERRORMSG"
	echo $ERRORMSG
	exit 1
fi
